name: Node.js

on:
  push:
  pull_request:

jobs:
  test:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test
      - run: npm pack
